version: "3.9"
services:
  # Backend service
  backend:
    build:
      context: ./Techdome-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Backend port 5000
    environment:
      - PORT=${PORT}
      - DB=${DB}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    depends_on:
      - mongo
    volumes:
      - ./Techdome-backend:/app
    networks:
      - techdome-network

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017" # MongoDB port
    volumes:
      - mongo-data:/data/db
    networks:
      - techdome-network

  # Frontend service
  frontend:
    build:
      context: ./Techdome-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React app port
    environment:
      - REACT_APP_API_URL=loacalhost:5000 # Set API URL for the frontend
    depends_on:
      - backend
    # volumes:
    #   - ./Techdome-frontend:/app
    networks:
      - techdome-network

volumes:
  mongo-data:

networks:
  techdome-network:
